# Generated by Django 4.2.2 on 2023-06-23 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('tech_skills', models.CharField(choices=[('P', 'Python'), ('j', 'Java'), ('r', 'Ruby'), ('d', 'Docker'), ('n', 'NodeJS')], max_length=50)),
            ],
            options={
                'db_table': 'Candidateinfo',
            },
        ),
    ]
