# Generated by Django 4.2.2 on 2023-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='number',
            field=models.IntegerField(),
        ),
    ]
