# Generated by Django 4.2.2 on 2023-06-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetails', '0002_alter_candidatedetails_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('tech_skills', models.JSONField()),
                ('resume_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'candidate_info',
            },
        ),
        migrations.DeleteModel(
            name='CandidateDetails',
        ),
    ]
