# Generated by Django 4.2.2 on 2023-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdetails', '0003_candidateinfo_delete_candidatedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='resume_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
